<?php
/**
 * This is the default template for the Savings
 * element in the totals loop of the content-confirmation
 * template part.
 *
 * 
 * @version 1.1.0
 * @package IT_Exchange
 *
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, copy over this file
 * to the exchange/content-confirmation/elements/
 * directory located in your theme.
*/
?>

<?php if ( it_exchange( 'transaction', 'has-billing-address' ) ) { ?>
<?php do_action( 'ninja_shop_content_confirmation_before_billing_address_element' ); ?>
<div class="ninja-shop-confirmation-billing-address-purchase-requirement ninja-shop-column">
	<h3><?php _e( 'Billing Address', 'it-l10n-ithemes-exchange' ); ?></h3>
    <div class="checkout-purchase-requirement-billing-address-options">
        <div class="existing-billing-address">
        <?php it_exchange( 'transaction', 'billing-address' ); ?>
        </div>
    </div>
</div>
<?php do_action( 'ninja_shop_content_confirmation_after_billing_address_element' ); ?>
<?php } ?>
