<?php
/**
 * This is the default template part for the
 * instructions in the transaction meta loop of
 * the Transaction Confirmation template part.
 *
 * 
 * @version 1.1.0
 * @package IT_Exchange
 *
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, simply copy over this
 * file's content to the exchange/content-confirmation/elements/
 * directory located in your theme.
*/
?>

<?php do_action( 'ninja_shop_content_confirmation_before_instructions_element' ); ?>
<div class="ninja-shop-transaction-instructions">
	<p><?php it_exchange( 'transaction', 'instructions' ); ?></p>
</div>
<?php do_action( 'ninja_shop_content_confirmation_before_instructions_element' ); ?>
