<?php
/**
 * This is the default template part for the line
 * item quantity and total element.
 *
 * 
 * @version 1.1.0
 * @package IT_Exchange
 *
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, copy over this file
 * to the exchange/content-confirmation/elements/ directory
 * located in your theme.
 */
$supports = it_exchange( 'line-item', 'supports-quantity' );
?>
<div class="ninja-shop-table-column ninja-shop-line-item-quantity-total-column">
	<div class="ninja-shop-table-column-inner">
		<span class="ninja-shop-line-item-quantity-column-part" style="<?php echo $supports ? '' : 'visibility: hidden;'; ?>">
			<?php it_exchange( 'line-item', 'quantity', 'format=var_value' ); ?>
		</span>
		<span class="ninja-shop-right ninja-shop-line-item-total-column-part"><?php it_exchange( 'line-item', 'total' ); ?></span>
	</div>
</div>
