<?php
/**
 * Default template part for when no transactions
 * are found on the transaction confirmation page.
 *
 * 
 * @version 1.1.0
 * @package IT_Exchange
 *
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, simply copy over this
 * file's content to the exchange/content-confirmation/elements/
 * directory located in your theme.
*/
?>

<?php do_action( 'ninja_shop_content_confirmation_before_not_found_element' ); ?>
<div class="ninja-shop-transaction-not-found">
	<p class="ninja-shop-error"><?php _e( 'No transactions found.', 'it-l10n-ithemes-exchange' ); ?></p>
</div>
<?php do_action( 'ninja_shop_content_confirmation_after_not_found_element' ); ?>
