<?php
/**
 * This is the default template part for the
 * order number in the transaction
 * confirmation template part.
 *
 * 
 * @version 1.1.0
 * @package IT_Exchange
 *
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, simply copy over this
 * file's content to the exchange/content-confirmation/elements/
 * directory located in your theme.
*/
?>

<?php do_action( 'ninja_shop_confirmation_before_transaction_order_number' ); ?>
<div class="ninja-shop-order-number">
	<p><?php it_exchange( 'transaction', 'order-number' ); ?></p>
</div>
<?php do_action( 'ninja_shop_confirmation_after_transaction_order_number' ); ?>
