<?php
/**
 * This is the default template part for the
 * purchases label for the transaction
 * confirmation template part.
 *
 * 
 * @version 1.1.0
 * @package IT_Exchange
 *
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, simply copy over this
 * file's content to the exchange/content-confirmation/elements/
 * directory located in your theme.
*/
?>

<?php do_action( 'ninja_shop_confirmation_before_transaction_purchases_label' ); ?>
<div class="ninja-shop-transaction-purchases-label">
	<h3><?php _e( 'Cart Items', 'it-l10n-ithemes-exchange' ); ?></h3>
</div>
<?php do_action( 'ninja_shop_confirmation_after_transaction_purchases_label' ); ?>
