<?php
/**
 * This is the default template part for the
 * total in the transaction meta loop of the
 * transaction Confirmation template part.
 *
 * 
 * @version 1.1.0
 * @package IT_Exchange
 *
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, simply copy over this
 * file's content to the exchange/content-confirmation/elements/
 * directory located in your theme.
*/
?>

<?php do_action( 'ninja_shop_confirmation_before_transaction_total_element' ); ?>
<div class="ninja-shop-transaction-total">
	<p><?php _e( 'Total:', 'it-l10n-ithemes-exchange' ); ?> <?php it_exchange( 'transaction', 'total' ); ?></p>
</div>
<?php do_action( 'ninja_shop_confirmation_after_transaction_total_element' ); ?>
