<?php
/**
 * The default template part for no transactions found in
 * the content-purchases template part's transactions loop.
 *
 * 
 * @version 1.1.0
 * @package IT_Exchange
 *
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, copy over this file
 * to the exchange/content-purchases/elements/ directory
 * located in your theme.
*/
?>

<?php do_action( 'ninja_shop_content_purchases_before_no_transaction_products_notice_element' ); ?>
<p class="ninja-shop-no-transaction-products-found ninja-shop-notice"><?php _e( 'No products found for this transaction', 'it-l10n-ithemes-exchange' ); ?></p>
<?php do_action( 'ninja_shop_content_purchases_after_no_transaction_products_after_element' ); ?>
