<?php
/**
 * The default template part for the product featured-image in
 * the content-store template part's product-images loop
 *
 * 
 * @version 1.1.0
 * @package IT_Exchange
 *
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, simply copy over this
 * file's content to the exchange/content-store/elements
 * directory located in your theme.
*/
?>

<?php if ( it_exchange( 'product', 'has-featured-image' ) ) : ?>
	<?php do_action( 'ninja_shop_content_store_before_featured_image_element' ); ?>
	<a class="ninja-shop-product-feature-image" href="<?php it_exchange( 'product', 'permalink', array( 'format' => 'url' ) ); ?>">
		<?php it_exchange( 'product', 'featured-image', array( 'size' => 'large' ) ); ?>
	</a>
	<?php do_action( 'ninja_shop_content_store_after_featured_image_element' ); ?>
<?php endif; ?>
