<?php
/**
 * The default template part for the product base
 * price in the content-product template part's
 * product-info loop.
 *
 * 
 * @version 1.1.0
 * @package IT_Exchange
 *
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, simply copy this file's
 * content to the exchange/content-product/elements
 * directory located in your theme.
*/
?>

<?php if ( it_exchange( 'product', 'has-base-price' ) ) : ?>
	<?php do_action( 'ninja_shop_content_product_before_base_price_element' ); ?>
	<div class="ninja-shop-product-price">
		<p><?php it_exchange( 'product', 'base-price' ); ?></p>
	</div>
	<?php do_action( 'ninja_shop_content_product_after_base_price_element' ); ?>
<?php endif; ?>
