<?php
/**
 * This is the default template part for the cart title row
 * items loop.
 *
 * 
 * @version 1.1.0
 * @package IT_Exchange
 *
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, copy over this file
 * to the exchange/content-cart/loops/ directory
 * located in your theme.
*/
?>
<div class="ninja-shop-table-row">
	<div class="ninja-shop-table-column ninja-shop-cart-title-thumbnail">
		<div class="ninja-shop-table-column-inner">
		</div>
	</div>
	<div class="ninja-shop-table-column ninja-shop-cart-title-product">
		<div class="ninja-shop-table-column-inner">
			<?php _e( 'Product', 'it-l10n-ithemes-exchange' ); ?>
		</div>
	</div>
	<div class="ninja-shop-table-column ninja-shop-cart-title-price">
		<div class="ninja-shop-table-column-inner">
			<?php _e( 'Price', 'it-l10n-ithemes-exchange' ); ?>
		</div>
	</div>
	<div class="ninja-shop-table-column ninja-shop-cart-title-quantity">
		<div class="ninja-shop-table-column-inner">
			<?php _e( 'Quantity', 'it-l10n-ithemes-exchange' ); ?>
		</div>
	</div>
	<div class="ninja-shop-table-column ninja-shop-cart-title-total">
		<div class="ninja-shop-table-column-inner">
			<?php _e( 'Total', 'it-l10n-ithemes-exchange' ); ?>
		</div>
	</div>
	<div class="ninja-shop-table-column ninja-shop-cart-title-remove">
		<div class="ninja-shop-table-column-inner">
		</div>
	</div>
</div>
