<?php
/**
 * This is the default template part for the
 * empty_cart element in the content-cart template
 * part.
 *
 * 
 * @version 1.1.0
 * @package IT_Exchange
 *
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, copy over this file
 * to the exchange/content-cart/elements/ directory
 * located in your theme.
*/
?>

<?php do_action( 'ninja_shop_content_cart_before_empty_element' ); ?>
<?php it_exchange( 'cart', 'empty' ); ?>
<?php do_action( 'ninja_shop_content_cart_after_empty_element' ); ?>
