<?php
/**
 * This is the default template for the Quantity
 * cart item element in the content-cart.php
 * template part.
 *
 * 
 * @version 1.1.0
 * @package IT_Exchange
 *
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, copy over this file
 * to the exchange/content-cart/elements/
 * directory located in your theme.
*/
?>

<?php do_action( 'ninja_shop_content_cart_before_item_quantity_element' ); ?>
<div class="ninja-shop-cart-item-quantity ninja-shop-table-column">
	<?php do_action( 'ninja_shop_content_cart_begin_item_quantity_element' ); ?>
	<div class="ninja-shop-table-column-inner">
		<?php it_exchange( 'cart-item', 'quantity' ); ?>
	</div>
	<?php do_action( 'ninja_shop_content_cart_end_item_quantity_element' ); ?>
</div>
<?php do_action( 'ninja_shop_content_cart_after_item_quantity_element' ); ?>
