<?php
/**
 * The main template file for the title element in
 * the cart-items loop for content-cart template
 * part.
 *
 * 
 * @version 1.1.0
 * @package IT_Exchange
 *
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, copy over this file
 * to the exchange/content-cart/elements/
 * directory located in your theme.
*/
?>

<?php do_action( 'ninja_shop_content_cart_before_item_title_element' ); ?>
<div class="ninja-shop-cart-item-title ninja-shop-table-column">
	<?php do_action( 'ninja_shop_content_cart_begin_item_title_element' ); ?>
	<div class="ninja-shop-table-column-inner">
		<a href="<?php it_exchange( 'cart-item', 'permalink' ); ?>"><?php it_exchange( 'cart-item', 'title' ); ?></a>
		<?php it_exchange( 'cart-item', 'description' ); ?>
	</div>
	<?php do_action( 'ninja_shop_content_cart_begin_item_title_element' ); ?>
</div>
<?php do_action( 'ninja_shop_content_cart_after_item_title_element' ); ?>
