<?php
/**
 * This is the default template part for the line
 * item name element.
 *
 * 
 * @version 1.1.0
 * @package IT_Exchange
 *
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, copy over this file
 * to the exchange/content-cart/loops/ directory
 * located in your theme.
 */
?>
<div class="ninja-shop-table-column ninja-shop-cart-item-price">
	<div class="ninja-shop-table-column-inner">
		<?php it_exchange( 'cart-item', 'price' ); ?>
	</div>
</div>
