<?php
/**
 * This is the default template part for the line
 * item child element.
 *
 * 
 * @version 1.1.0
 * @package IT_Exchange
 *
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, copy over this file
 * to the exchange/content-cart/loops/ directory
 * located in your theme.
 */
?>
<div class="ninja-shop-table-row ninja-shop-line-item ninja-shop-<?php it_exchange( 'line-item', 'type', 'label=0' ); ?>-item">
	<div class="ninja-shop-table-column ninja-shop-column-offset" style="width: 10%;"></div>
	<?php it_exchange_get_template_part( 'content-cart/elements/line-item-name' ); ?>
	<?php it_exchange_get_template_part( 'content-cart/elements/line-item-quantity' ); ?>
	<?php it_exchange_get_template_part( 'content-cart/elements/line-item-total' ); ?>
	<div class="ninja-shop-table-column ninja-shop-column-offset" style="width: 7%;"></div>
</div>
