<?php
/**
 * This is the default template part for the
 * rememberme element in the super-widget-login template
 * part.
 *
 * 
 * @version 1.1.0
 * @package IT_Exchange
 *
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, copy over this file
 * to the exchange/super-widget-login/elements/
 * directory located in your theme.
*/
?>

<?php do_action( 'ninja_shop_super_widget_login_before_rememberme_element' ); ?>
<div class="ninja-shop-rememberme">
	<?php it_exchange( 'login', 'rememberme' ); ?>
</div>
<?php do_action( 'ninja_shop_super_widget_login_after_rememberme_element' ); ?>
