<?php
/**
 * The default download-info loop for the
 * content-downloads.php template part.
 *
 * 
 * @version 1.1.0
 * @package IT_Exchange
 *
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, simply copy this file's
 * content to the exchange/content-download/loops
 * directory located in your theme.
*/
?>
<?php if ( it_exchange( 'transaction', 'has-product-downloads' ) ) : ?>
	<?php do_action( 'ninja_shop_content_downloads_before_download_info_wrap' ); ?>
	<div class="ninja-shop-download-wrapper">
		<?php do_action( 'ninja_shop_content_downloads_before_download_info_loop' ); ?>
		<?php while ( it_exchange( 'transaction', 'product-downloads' ) ) : ?>
			<?php do_action( 'ninja_shop_content_downloads_begin_download_info_loop' ); ?>
			<div class="ninja-shop-download">
				<?php it_exchange_get_template_part( 'content-downloads/elements/confirmation-url' ); ?>
				<div class="ninja-shop-download-info">
                    <?php it_exchange_get_template_part( 'content-downloads/elements/download-title' ); ?>
					<?php if ( it_exchange( 'transaction', 'has-product-download-hashes' ) ) : ?>
						<?php it_exchange_get_template_part( 'content-downloads/loops/download-data' ); ?>
					<?php endif; ?>
				</div>
			</div>
			<?php do_action( 'ninja_shop_content_downloads_end_download_info_loop' ); ?>
		<?php endwhile; ?>
		<?php do_action( 'ninja_shop_content_downloads_after_download_info_loop' ); ?>
	</div>
	<?php do_action( 'ninja_shop_content_downloads_after_download_info_wrap' ); ?>
<?php endif; ?>
