<?php
/**
 * This is the default template part for the
 * login element in the content-registration
 * template part.
 *
 * 
 * @version 1.1.0
 * @package IT_Exchange
 *
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, copy over this file
 * to the exchange/content-registration/elements/
 * directory located in your theme.
*/
?>

<?php do_action( 'ninja_shop_content_registration_before_login_element' ); ?>
<div class="ninja-shop-registration-login">
	<a href="<?php esc_attr_e( it_exchange_get_page_url( 'login' ) ); ?>"><?php _e( 'Log in', 'it-l10n-ithemes-exchange' ); ?></a>
</div>
<?php do_action( 'ninja_shop_content_registration_after_login_element' ); ?>
