<?php
/**
 * This is the default template part called by
 * content-registration when user is already logged in.
 *
 * 
 * @version 1.1.0
 * @package IT_Exchange
 *
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, copy over this file
 * to the exchange/content-registration/elements/
 * directory located in your theme.
*/
?>

<?php do_action( 'ninja_shop_content_registration_before_user_logged_in_element' ); ?>
<p class="ninja-shop-registration-logged-in">
	<?php printf( __( 'You already have an active account and are logged in. Visit your %sProfile%s', 'it-l10n-ithemes-exchange' ), '<a href="' . it_exchange_get_page_url( 'profile' ) . '">', '</a>' ); ?>
</p>
<?php do_action( 'ninja_shop_content_registration_before_user_logged_in_element' ); ?>
