<?php
/**
 * This is the default template part for the save
 * button element in the content-profile template
 * part.
 *
 * 
 * @version 1.1.0
 * @package IT_Exchange
 *
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, copy over this file
 * to the exchange/content-profile/elements/
 * directory located in your theme.
*/
?>

<?php do_action( 'ninja_shop_content_profile_before_save_button_element' ); ?>
<div class="ninja-shop-customer-save ninja-shop-profile-save">
	<?php it_exchange( 'customer', 'save' ); ?>
</div>
<?php do_action( 'ninja_shop_content_profile_after_save_button_element' ); ?>
