<?php
/**
 * This is the default template part for the
 * website element in the content-profile template
 * part.
 *
 * 
 * @version 1.1.0
 * @package IT_Exchange
 *
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, copy over this file
 * to the exchange/content-profile/elements/
 * directory located in your theme.
*/
?>

<?php do_action( 'ninja_shop_content_profile_before_website_element' ); ?>
<div class="ninja-shop-customer-website">
	<?php it_exchange( 'customer', 'website' ); ?>
</div>
<?php do_action( 'ninja_shop_content_profile_after_website_element' ); ?>
