<?php
/**
 * The default transaction-info loop for the content-purchases.php template part
 *
 * 
 * @version 1.1.0
 * @package IT_Exchange
 *
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, copy over this file
 * to the exchange/content-purchases/loops/ directory
 * located in your theme.
*/
?>

<?php do_action( 'ninja_shop_content_purchases_before_transaction_products_loop' ); ?>
<?php while( it_exchange( 'transaction', 'products' ) ) : ?>
<?php do_action( 'ninja_shop_content_purchases_begin_transaction_products_loop' ); ?>
	<?php do_action( 'ninja_shop_content_purchases_begin_transaction_products' ); ?>
	<div class="ninja-shop-purchase-items">
		<div class="ninja-shop-item-info">
			<div class="ninja-shop-item-thumbnail">
				<?php it_exchange_get_template_part( 'content-purchases/elements/product-featured-image' ); ?>
			</div>
			<div class="ninja-shop-item-data">
				<?php it_exchange_get_template_part( 'content-purchases/loops/product-info' ); ?>
			</div>
		</div>
	</div>
	<?php do_action( 'ninja_shop_content_purchases_end_transaction_products' ); ?>
<?php do_action( 'ninja_shop_content_purchases_end_transaction_products_loop' ); ?>
<?php endwhile; ?>
<?php do_action( 'ninja_shop_content_purchases_after_transaction_products_loop' ); ?>
