<?php
/**
 * This is the default template for the Easy U.S. Sales Taxes
 * element in the totals loop of the content-cart
 * template part. It was added by Easy U.S. Sales Taxes add-on.
 *
 * 
 * @version 1.1.0
 * @package exchange-addon-easy-us-sales-taxes
 *
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, copy over this file
 * to the exchange/content-cart/elements/
 * directory located in your theme.
*/
?>

<?php do_action( 'ninja_shop_super_widget_checkout_before_basic_us_sales_taxes_element' ); ?>
<div class="cart-taxes cart-totals-row">
	<?php do_action( 'ninja_shop_super_widget_checkout_begin_basic_us_sales_taxes_element' ); ?>
	<?php _e( 'Tax', 'LION' ) . _x( ':', 'Used in superwidget for taxes. eg Tax: ', 'LION' ); ?>
	<?php it_exchange( 'us-taxes', 'taxes' ); ?>
	<?php do_action( 'ninja_shop_super_widget_checkout_end_basic_us_sales_taxes_element' ); ?>
</div>
<?php do_action( 'ninja_shop_super_widget_checkout_after_basic_us_sales_taxes_element' ); ?>
