<?php
/**
 * This is the default template part for the
 * registration disabled-message element in the registration loop for the
 * purchase-requriements in the content-checkout
 * template part.
 *
 * 
 * @version 1.1.0
 * @package IT_Exchange
 *
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, copy over this file to the
 * /exchange/content-checkout/elements/purchase-requirements/logged-in/elements/registration
 * directory located in your theme.
*/
?>
<?php do_action( 'ninja_shop_content_checkout_logged_in_purchase_requirement_registration_before_disabled_message_element' ); ?>
<p class="ninja-shop-registration-disabled ninja-shop-notice">
	<?php it_exchange( 'registration', 'disabled-message' ); ?>
</p>
<?php do_action( 'ninja_shop_content_checkout_logged_in_purchase_requirement_registration_after_disabled_message_element' ); ?>
