<?php
/**
 * This is the default template for the
 * super-widget-billing-address addresses loop.
 *
 * 
 * @version 1.1.0
 * @package IT_Exchange
 *
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, copy over this file
 * to the exchange/super-widget-billing-address/loops directory
 * located in your theme.
 */
?>
<?php if ( it_exchange( 'customer', 'has-addresses' ) ) : ?>
	<ul class="ninja-shop-existing-addresses-selector ninja-shop-existing-addresses-selector--billing">
		<?php while ( it_exchange( 'customer', 'addresses' ) ) : ?>
			<li><?php it_exchange( 'billing', 'radio-existing' ); ?></li>
		<?php endwhile; ?>
		<li>
			<?php it_exchange( 'billing', 'radio-new' ); ?>
		</li>
	</ul>
<?php endif; ?>
