<?php
/**
 * Default template for displaying a customer
 * downloads.
 *
 * 
 * @version 1.1.0
 * @link http://ithemes.com/codex/page/Exchange_Template_Updates
 * @package IT_Exchange
 *
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, simply copy this file's
 * content to the exchange directory located in your
 * theme.
*/
?>

<?php do_action( 'ninja_shop_content_downloads_before_wrap' ); ?>
<div id="ninja-shop-downloads" class="ninja-shop-wrap ninja-shop-account">
	<?php do_action( 'ninja_shop_content_downloads_begin_wrap' ); ?>
	<?php it_exchange_get_template_part( 'messages' ); ?>
	<?php it_exchange( 'customer', 'menu' ); ?>
	<?php it_exchange_get_template_part( 'content-downloads/loops/transaction' ); ?>
	<?php do_action( 'ninja_shop_content_downloads_end_wrap' ); ?>
</div>
<?php do_action( 'ninja_shop_content_downloads_after_wrap' ); ?>
