<?php
/**
 * Default template for displaying the a single
 * exchange product.
 *
 * 
 * @version 1.1.0
 * @link http://ithemes.com/codex/page/Exchange_Template_Updates
 * @package IT_Exchange
 *
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, simply copy over this
 * file's content to the exchange directory located
 * in your theme.
*/
?>

<?php do_action( 'ninja_shop_content_product_before_wrap' ); ?>
<div id="ninja-shop-product" class="ninja-shop-wrap">
	<?php it_exchange_get_template_part( 'messages' ); ?>
	<?php do_action( 'ninja_shop_content_product_begin_wrap' ); ?>
	<div class="ninja-shop-product-standard-content ninja-shop-columns-wrapper <?php echo ( ! it_exchange( 'product', 'has-images' ) ) ? ' ninja-shop-product-no-images' : 'ninja-shop-product-has-images'; ?>">
		<div class="ninja-shop-column ninja-shop-product-info">
			<div class="ninja-shop-column-inner">
				<?php it_exchange_get_template_part( 'content-product/loops/product-info' ); ?>
			</div>
		</div>
		<?php it_exchange_get_template_part( 'content-product/loops/product-images' ); ?>
	</div>

	<div class="ninja-shop-product-advanced-content">
		<?php it_exchange_get_template_part( 'content-product/loops/product-advanced' ); ?>
	</div>
	<?php do_action( 'ninja_shop_content_product_end_wrap' ); ?>
</div>
<?php do_action( 'ninja_shop_content_product_after_wrap' ); ?>
