<?php
/**
 * Default template for displaying the an exchange
 * customer's profile.
 *
 * 
 * @version 1.1.0
 * @link http://ithemes.com/codex/page/Exchange_Template_Updates
 * @package IT_Exchange
 *
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, simply copy over this
 * file's content to the exchange/ directory located
 * in your theme.
*/
?>

<?php do_action( 'ninja_shop_content_profile_before_wrap' ); ?>
<div id="ninja-shop-profile" class="ninja-shop-wrap ninja-shop-account">
<?php do_action( 'ninja_shop_content_profile_begin_wrap' ); ?>
	<?php it_exchange_get_template_part( 'messages' ); ?>
	<?php it_exchange( 'customer', 'menu' ); ?>
	<?php do_action( 'ninja_shop_content_profile_before_form' ); ?>
	<?php it_exchange( 'customer', 'formopen' ); ?>
		<?php it_exchange_get_template_part( 'content-profile/loops/fields' ); ?>
		<?php it_exchange_get_template_part( 'content-profile/loops/actions' ); ?>
	<?php it_exchange( 'customer', 'formclose' ); ?>
	<?php do_action( 'ninja_shop_content_profile_after_form' ); ?>
<?php do_action( 'ninja_shop_content_profile_end_wrap' ); ?>
</div>
<?php do_action( 'ninja_shop_content_profile_after_wrap' ); ?>
