<?php
/**
 * The shipping address template for the Super Widget.
 *
 * 
 * @version 1.1.0
 * @link http://ithemes.com/codex/page/Exchange_Template_Updates
 * @package IT_Exchange
 *
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, simply copy over this
 * file's content to the exchange directory located
 * at your templates root.
*/
?>
<?php do_action( 'ninja_shop_super_widget_shipping_address_before_wrap' ); ?>
<div class="shipping-address ninja-shop-sw-processing-shipping-address">
	<?php do_action( 'ninja_shop_super_widget_shipping_address_begin_wrap' ); ?>
	<?php it_exchange_get_template_part( 'messages' ); ?>
	<h3><?php _e( 'Shipping Address', 'it-l10n-ithemes-exchange' ); ?></h3>

	<?php if ( it_exchange_get_next_purchase_requirement_property( 'slug' ) === 'shipping-address' && it_exchange_get_cart_shipping_address() ) : ?>
        <ul class="ninja-shop-messages ninja-shop-errors">
            <li><?php echo it_exchange_get_next_purchase_requirement_property( 'notification' ); ?></li>
        </ul>
	<?php endif; ?>

	<form class="ninja-shop-sw-shipping-address">
	<?php it_exchange_get_template_part( 'super-widget-shipping-address/loops/addresses' ); ?>
	<?php it_exchange_get_template_part( 'super-widget-shipping-address/loops/fields' ); ?>
	<?php it_exchange_get_template_part( 'super-widget-shipping-address/loops/actions' ); ?>
	</form>
	<?php do_action( 'ninja_shop_super_widget_shipping_address_end_wrap' ); ?>
</div>
<?php do_action( 'ninja_shop_super_widget_shipping_address_after_wrap' ); ?>
