<?php
/**
 * The billing address template for the Super Widget.
 *
 * 
 * @version 1.1.0
 * @link http://ithemes.com/codex/page/Exchange_Template_Updates
 * @package IT_Exchange
 *
 * WARNING: Do not edit this file directly. To use
 * this template in a theme, simply copy over this
 * file's content to the exchange directory located
 * at your templates root.
*/
?>
<?php do_action( 'ninja_shop_super_widget_billing_address_before_wrap' ); ?>
<div class="billing-address ninja-shop-sw-processing-billing-address">
	<?php do_action( 'ninja_shop_super_widget_billing_address_begin_wrap' ); ?>
	<?php it_exchange_get_template_part( 'messages' ); ?>
	<h3><?php _e( 'Billing Address', 'it-l10n-ithemes-exchange' ); ?></h3>
	<form class="ninja-shop-sw-billing-address">
	<?php it_exchange_get_template_part( 'super-widget-billing-address/loops/addresses' ); ?>
	<?php it_exchange_get_template_part( 'super-widget-billing-address/loops/fields' ); ?>
	<?php it_exchange_get_template_part( 'super-widget-billing-address/loops/actions' ); ?>
	</form>
	<?php do_action( 'ninja_shop_super_widget_billing_address_end_wrap' ); ?>
</div>
<?php do_action( 'ninja_shop_super_widget_billing_address_after_wrap' ); ?>
